# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparrayfire_hello_world <- function() {
    .Call('_anRpackage_rcpparrayfire_hello_world', PACKAGE = 'anRpackage')
}

rcpparrayfire_outerproduct <- function(x) {
    .Call('_anRpackage_rcpparrayfire_outerproduct', PACKAGE = 'anRpackage', x)
}

rcpparrayfire_innerproduct <- function(x) {
    .Call('_anRpackage_rcpparrayfire_innerproduct', PACKAGE = 'anRpackage', x)
}

rcpparrayfire_bothproducts <- function(x) {
    .Call('_anRpackage_rcpparrayfire_bothproducts', PACKAGE = 'anRpackage', x)
}

